### ISSUE TITLE
NDEF Tag Emulation

### ISSUE THREAD

**Issue by blacktorch** [ElectronicCats/ElectronicCats-PN7150#33]
Is there any example on how to use the ndef tag emulation, or api reference.

**Comment by jazhe** [comment]
Hello @blacktorch!
Unfortunately, the example to NDEF is still in the review process. In order to know the status and the latest actualizations, you can check the [Pull Request here](https://github.com/ElectronicCats/ElectronicCats-PN7150/pull/25).
If you have any further queries do not hesitate to open a new issue, we are here to help!

**Comment by sabas1080** [comment]
#25

**Comment by sabas1080** [comment]
now available
