### ISSUE TITLE
What is the response to a CORE_RESET_CMD command with the PN7150 device?

### ISSUE THREAD

**Issue by DominusDRR** [ElectronicCats/ElectronicCats-PN7150#37]
Hi.

When sending the CORE_RESET_CMD, three response bytes are obtained, which are:

0x40, 0x00 and 0x03

In your code simply return an error when "waking up" the NFC

`(void)writeData(NCICoreReset, 4);
    getMessage(15);
    NbBytes = rxMessageLength;
    if ((NbBytes == 0) || (rxBuffer[0] != 0x40) || (rxBuffer[1] != 0x00))
    {
        return ERROR;
    }`

If that happens, what does it mean? What can be done to solve the problem?

I have consulted the NCI specification and there is no information about the values for these 3 bytes.

**Comment by Eric286** [comment]
Dear @DominusDRR !

Thank you for contacting us.

Byte 0x00 would be STATUS_OK

Byte 0x03 would be STATUS_FAILED

Byte 0x40 is in other words more special than the other two since it does not only refer to whether the status is good or not.  It would be MFC_Authenticate_REQ (DH asks NFCC to perform MFC authenticate)

"If that happens, what does it mean? What can be done to solve the problem?"

Here what it means is that when you get the message if it does see a byte with 0x40 or 0x00, which would be, the bytes that you get when the status is correct, it will write the data to the board.
But nevertheless, if it does not find any of these two, and finds that the message contains nothing, it would mean that the response was 0x03, which only occurs when the Status fails.

Possible errors to this can be, a wrong key, a time-out triggered during authentication, you are performing two same commands before this, or no message found to write.

Have a nice day!
Kind regards!
Electronic Cats Support Team.

**Comment by DominusDRR** [comment]
Hi. Thanks for answering

One last question, the 0x40, in which part of the NCI specification does it fit?

![image](https://user-images.githubusercontent.com/43682132/187548174-da03e79d-da81-4cd1-b215-d6c821852f67.png)

According to your answer, if I have not misunderstood, the second byte would be Status (0x00), while the third byte (0x03) would be the NCI version:

If so, there is no match with CORE_RESET_RSP
from Table 5.


![image](https://user-images.githubusercontent.com/43682132/187548744-81bb291d-a932-4c74-bc28-ed29fec53194.png)

**Comment by DominusDRR** [comment]
Hi,

I think that 0x40 is the header of the frame, it indicates a response to a command sent from the DH (microcontroller)

![image](https://user-images.githubusercontent.com/43682132/187551332-826faca9-7e68-4379-b441-fc0f285a06c2.png)

**Comment by Eric286** [comment]
Hello @DominusDRR!

Just one thing where did you get the pictures from? (In order to better understand the situation.)

0x40, what it does is ask the NFCC to make an MFC authentication command, with this, name MFC_Authenticate_REQ, to later obtain the MFC Authenticate command status with this name MFC_Authenticate_RSP

So to speak the byte works like REQuest and ReSPonse (REQ and ReSP)

![image](https://user-images.githubusercontent.com/40640735/187553175-e14c5b3c-ea15-4311-a893-12c566f85e9a.png)


Have a nice day!
Kind regards!
Electronic Cats Support Team.

**Comment by DominusDRR** [comment]
The images were taken from the document called NFC Controller Interface (NCI) Specification and PN7150 User Manual (UM10936)

And it looks like I'm right, the 0x40 has nothing to do with MFC_Authenticate_RSP yet.

The frames have an initial header where it is indicated that they are, for example for CORE_RESET_CMD, according to your own example, 0x20 is sent, which corresponds to

![image](https://user-images.githubusercontent.com/43682132/187554417-1636de8f-e4e9-4f03-8199-1fd591699bdb.png)

![image](https://user-images.githubusercontent.com/43682132/187554534-5e21fed0-12f0-48ae-b8e3-a215727ea614.png)

And if the NFC responds to the command, the header is 0x40

![image](https://user-images.githubusercontent.com/43682132/187554628-6f17ad28-7578-4610-95a1-21fdbad830c6.png)

Pag 15:

[https://www.nxp.com/docs/en/user-guide/UM10936.pdf](url)

**Comment by salmg** [comment]
Hello @DominusDRR 

Yes, you are partially right. The 0x40, it is a response message. It is a combination of MT values + PBF(Packet Boundary Flag) + GID (Group Identifier)

0x00 is 1 bit RFU + 1 bit RFU + 6 bits for Opcode identifier(OID) which basically indicates the level of the previous executed command. In this case 0x00 which means that the command executed is level 0, the first level of commands that could be executed in the PN*. Other type of commands on the same level are CORE_RESET_RSP or CORE_RESET_NTF, for example. You can find the completed list in the Table 102 in the NFC Controller Interface (NCI) Specification from the NFC Forum version 1.0. 

0x03 is the payload length.
![image](https://user-images.githubusercontent.com/7434935/187574837-ae0bb874-a024-4b43-a350-b48b280ec24f.png)

Answering the main question, the core reset helps to write specific core configuration when the PN initializes, establishing a previous configuration. If it fails, means that the previous configuration using the ...CORE_CONF command was not applied correctly and that could be for many different factors.

**Comment by DominusDRR** [comment]
Thanks for the explanation. So in the payload (which is 3 bytes) there would be the Status, NCI Version and Configuration Status:

Regards
